name: On PR

on:
  pull_request:
  merge_group:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for pushing version bump
  pull-requests: write # This is required for commenting back to a PR the pytest coverage report

jobs:

  hadolint-pr:
    uses: Synthesia-Technologies/gha-workflows/.github/workflows/hadolint.yaml@main
    with:
      dockerfile: docker/Dockerfile

  python-end-to-end-pr:
    if: ${{ github.event_name != 'merge_group' }}
    uses: ./.github/workflows/python_end_to_end.yml
    with:
      arn-role: arn:aws:iam::812634467557:role/gha-syntheticactors-role
      generate-pytest-coverage: "false"
    secrets:
      GHA_RNDUVPC_DEPLOY_KEY: ${{ secrets.GHA_RNDUVPC_DEPLOY_KEY }}

  # build-and-push-docker-image-pr:
  #   needs: python-end-to-end-pr
  #   if: ${{ github.event_name != 'merge_group' }}
  #   uses: ./.github/workflows/build_and_push_docker_image.yml
  #   with:
  #     arn-role: arn:aws:iam::812634467557:role/gha-nlp-role
  #     docker-image-name: synthesia-rnd-channels-last-groupnorm
  #     docker-image-tags: "dev, ${{ needs.python-end-to-end-pr.outputs.package-base-version }}.dev0-${{ github.event.pull_request.head.sha }}"
  #     pip-package-name: synthesia-rnd-channels-last-groupnorm
  #     pip-package-version: "${{ needs.python-end-to-end-pr.outputs.package-dev-version }}"
  #     python-package-name: channels_last_groupnorm
